name: Purge Camo Cache

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  purge-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Purge Camo Cache
        uses: kevincobain2000/action-camo-purge@v1